### ISSUE TITLE
Crashes when opens

### ISSUE THREAD

**Issue by Shiori857** [Piotrekol/StreamCompanion#102]
When I open the program, this error message shows up:
Field not found: 'StreamCompanionTypes.DataTypes.MapSearchResult.Action'.
   at osuOverlay.IngameOverlay.SetNewMap(MapSearchResult map)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.SetNewMap(MapSearchResult map)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.ProcessMapResult(MapSearchResult mapSearchResult)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MapStringFormatter.ConsumerTask()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by Piotrekol** [comment]
Update ingameOverlay plugin with current version or remove osuOverlay.dll in SC Plugins folder

**Comment by Shiori857** [comment]
ok sorry about that. will do
