### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iiS1lver** [Piotrekol/StreamCompanion#129]
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at osu_StreamCompanion.Code.Core.Initializer.GetPlugins()
   at osu_StreamCompanion.Code.Core.Initializer.Start()
   at osu_StreamCompanion.Program.Main(String[] args)

**Comment by Piotrekol** [comment]
Please provide more information...

**Comment by iiS1lver** [comment]
Thats all the details that it has.

**Comment by iiS1lver** [comment]
https://gyazo.com/16b3ff98996b006ce9fb375c3a2d57c6
