### ISSUE TITLE
StreamCompanion crashing on install

### ISSUE THREAD

**Issue by joshuattd** [Piotrekol/StreamCompanion#155]
I am getting this error report when trying to use StreamCompanion.

Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at ProcessMemoryDataFinder.API.MemoryReader.<GetMemoryAddresses>d__16.MoveNext()
   at ProcessMemoryDataFinder.API.MemoryReader.FindPattern(Byte[] btPattern, String strMask, Int32 nOffset, Boolean useMask)
   at ProcessMemoryDataFinder.API.SigEx.ResolveAddress()
   at ProcessMemoryDataFinder.API.SigEx.GetValue(UInt32 size)
   at ProcessMemoryDataFinder.API.SigEx.GetInt()
   at OsuMemoryDataProvider.OsuMemoryReader.GetInt(Int32 signatureId)
   at OsuMemoryDataProvider.OsuMemoryReader.GetCurrentStatus(Int32& statusNumber)
   at OsuMemoryEventSource.MemoryListener.Tick(IOsuMemoryReader reader, Boolean sendEvents)
   at OsuMemoryEventSource.OsuMemoryEventSourceBase.TimerTick()
   at OsuMemoryEventSource.OsuMemoryEventSourceBase.TimerCallback(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Piotrekol** [comment]
Are you running osu as an administrator?(don't do that)
Have you tried running the newest build?
https://ci.appveyor.com/api/buildjobs/cnk4l0vve8fiet08/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe
