### ISSUE TITLE
Random "unhandled problem" keeps popping up at startup

### ISSUE THREAD

**Issue by DragoNiiSan** [Piotrekol/StreamCompanion#199]
when starting up the latest release of streamcompanion a popup shows saying "there was unhandled problem with a program and it needs to exit."
when click on "ok" this is what is says:

A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

**Comment by Piotrekol** [comment]
Try again using build above (you can find it above this message [or by clicking here](https://ci.appveyor.com/api/buildjobs/wlvqh43braa2ygt1/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe)) it should give more information about the problem

also execute this command in powershell and paste its output here:
```
Get-Process -Id (Get-NetTCPConnection -LocalPort 28390).OwningProcess
```

**Comment by DragoNiiSan** [comment]
Output:

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
   5342       0      192        148                 4   0 System

**Comment by DragoNiiSan** [comment]
Heres a better view:
![image](https://user-images.githubusercontent.com/71599466/93717189-0b216880-fb6c-11ea-8153-0a43968c19a9.png)

**Comment by DragoNiiSan** [comment]
Used the version you sent me and this pops up:
AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
SocketErrorCode: AccessDenied, ErrorCode: 10013
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at EmbedIO.Net.Internal.EndPointListener..ctor(HttpListener listener, IPAddress address, Int32 port, Boolean secure)
   at EmbedIO.Net.EndPointManager.<>c__DisplayClass9_0.<GetEpListener>b__1(Int32 x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at EmbedIO.Net.EndPointManager.GetEpListener(String host, Int32 port, HttpListener listener, Boolean secure)
   at EmbedIO.Net.EndPointManager.AddPrefix(String p, HttpListener listener)
   at EmbedIO.Net.EndPointManager.AddListener(HttpListener listener)
   at EmbedIO.Net.HttpListener.Start()
   at EmbedIO.WebServer.Prepare(CancellationToken cancellationToken)
   at EmbedIO.WebServerBase`1.<RunAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebSocketDataSender.WebSocketDataGetter.<RunServer>d__32.MoveNext()

**Comment by Piotrekol** [comment]
Build above should mitigate the issue - it should automatically change the used web overlay port at startup

**Comment by Piotrekol** [comment]
can you also paste the output of:
```
netsh int ipv4 show excludedportrange protocol=tcp
```

**Comment by DragoNiiSan** [comment]
![image](https://user-images.githubusercontent.com/71599466/93718121-eaf4a800-fb71-11ea-9e46-25abfb67102c.png)

**Comment by Piotrekol** [comment]
Thank you, since there are quite a few users affected by this, the default port used for web overlay will be changed in the next release.
Did the new build fix the issue for you?

**Comment by DragoNiiSan** [comment]
i'll test it and see for you soon
kinda at work atm
just left home :P

**Comment by DragoNiiSan** [comment]
Just to verify is the new build the one you had hyperlinked above?

**Comment by Piotrekol** [comment]
this is the link for the build: https://ci.appveyor.com/api/buildjobs/673rp9lb9x6cxsb0/artifacts/innoSetup%2FOutput%2FStreamCompanion%20Setup.exe
and this is for the future :)
![image](https://user-images.githubusercontent.com/4990365/93743884-284c4a80-fbf1-11ea-9e93-c834efac72da.png)

![2](https://i.imgur.com/CBBIwad.png)

**Comment by DragoNiiSan** [comment]
Yep, the linked one works. Thanks a lot!
