### ISSUE TITLE
[Bug] StreamCompanion crashing after updating to latest version

### ISSUE THREAD

**Issue by Hexality** [Piotrekol/StreamCompanion#215]
NullReferenceException: Object reference not set to an instance of an object.
   at LiveVisualizer.LiveVisualizerPlugin.ProcessNewMap(MapSearchResult mapSearchResult)
   at LiveVisualizer.LiveVisualizerPluginBase.<>c__DisplayClass27_0.<SetNewMap>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LiveVisualizer.LiveVisualizerPluginBase.<SetNewMap>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Piotrekol** [comment]
Was already fixed for a while.

Seeing that this does affect a fair bit of users I've pushed an early release.
