### ISSUE TITLE
Web App not working

### ISSUE THREAD

**Issue by Zonthem** [Piotrekol/StreamCompanion#243]
Hello

I've updated StreamCompanion today and after rebooting the computer i face a problem where no web overlay is loading. The 4 standard and a custom i made stay all blank, loading default data.

On the browser console i got 
`WebSocket connection to 'ws:<URL>/tokens' failed: WebSocket is closed before the connection is established.`

And the logs are displaying a single error 
```[Deb] 19:25:06 [ WebSocketDataGetter] - [HYevf28+tUKXH7SgrOhMQA] GET /favicon.ico: "404 Not Found" sent in 7ms (0 bytes)
EmbedIO.HttpException: Exception of type 'EmbedIO.HttpException' was thrown.
   at EmbedIO.Files.FileRequestHandler.ThrowNotFound(IHttpContext context, MappedResourceInfo info)
   at EmbedIO.Files.FileModule.OnRequestAsync(IHttpContext context)
   at EmbedIO.WebModuleBase.HandleRequestAsync(IHttpContext context)
   at EmbedIO.HttpExceptionHandler.Handle(String logSource, IHttpContext context, Exception exception, HttpExceptionHandlerCallback handler)
   at EmbedIO.WebModuleBase.HandleRequestAsync(IHttpContext context)
   at EmbedIO.Internal.WebModuleCollection.DispatchRequestAsync(IHttpContext context)
   at EmbedIO.WebServerBase`1.DoHandleContextAsync(IHttpContextImpl context)
[Deb] 19:25:10 [ WebSocketDataGetter] - [7I6MjwrMFECZnTXZV3SMCA] GET /tokens: "200 OK" sent in 5625ms (0 bytes)
```

**Comment by Piotrekol** [comment]
try reinstalling SC (backup your settings.ini/custom overlays first)
