### ISSUE TITLE
StreamCompanion crashes on certain maps

### ISSUE THREAD

**Issue by LemurWasHere** [Piotrekol/StreamCompanion#272]
So StreamCompanion crashes once I select certain maps. It works fine on like 99.5% of the maps, but once I go to certain maps in the song select it crashes. I also suck at debugging so I cant figure it out myself :D

**Comment by LemurWasHere** [comment]
> The error code:
NullReferenceException: Object reference not set to an instance of an object.
   at StreamCompanion.Common.CancelableAsyncLazy`1.GetValueAsync(CancellationToken cancellationToken)
   at StreamCompanion.Common.MapSearchResultsExtensions.GetPpCalculator(IMapSearchResult mapSearchResult, CancellationToken cancellationToken)
   at BeatmapPpReplacements.PpReplacements.CreateTokensAsync(IMapSearchResult map, CancellationToken cancellationToken)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.<>c__DisplayClass10_0.<<ProcessMapResult>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at osu_StreamCompanion.Code.Core.Maps.Processing.OsuEventHandler.HandleMapSearchResult(IMapSearchResult mapSearchResult)
   at osu_StreamCompanion.Code.Core.Maps.Processing.OsuEventHandler.OsuEventWorkerLoop()

**Comment by Piotrekol** [comment]
already fixed in prerelease build https://github.com/Piotrekol/StreamCompanion/commit/9390b31fac8791bb985845376c97f77b7ac318c0

The current pre-release build can be found here https://ci.appveyor.com/project/Piotrekol/streamcompanion/builds/38330173/artifacts

Will close this once next release gets published.
