### ISSUE TITLE
Error when trying to play with Streamcompanion

### ISSUE THREAD

**Issue by Ouzelot** [Piotrekol/StreamCompanion#276]
Hey,
I get a Error everytime I try to play osu with Streamcompanion.

Error:
NullReferenceException: Object reference not set to an instance of an object.
at StreamCompanion.Common.CancelableAsyncLazy`1.GetValueAsync(CancellationToken cancellationToken)
at StreamCompanion.Common.MapSearchResultsExtensions.GetPpCalculator(IMapSearchResult mapSearchResult, CancellationToken cancellationToken)
at BeatmapPpReplacements.PpReplacements.CreateTokensAsync(IMapSearchResult map, CancellationToken cancellationToken)
at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.<>c__DisplayClass10_0.<<ProcessMapResult>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at osu_StreamCompanion.Code.Core.Maps.Processing.OsuEventHandler.HandleMapSearchResult(IMapSearchResult mapSearchResult)
at osu_StreamCompanion.Code.Core.Maps.Processing.OsuEventHandler.OsuEventWorkerLoop()

I couldn't find anything related to this issue. Does someone know how to fix this?

**Comment by Piotrekol** [comment]
download newest pre-release https://github.com/Piotrekol/StreamCompanion/issues/272
