### ISSUE TITLE
StreamCompanion crashes with AggregateException / NullReferenceException ~30 seconds after starting osu.

### ISSUE THREAD

**Issue by cchamberlain** [Piotrekol/StreamCompanion#328]
Since installing latest version I have a new null reference exception showing up. It always seems to happen about 30 seconds after starting up osu. Prior to that everything appears to be working then I get this popup, then the following error window.

I tried installing the .NET 5.0 desktop runtime (x64) and have restarted multiple times etc. Tried running as admin and non-admin and experience same effect both places.

![image](https://user-images.githubusercontent.com/424694/138196499-519f7246-ab6e-4ca8-a59c-f76a43f90424.png)

![image](https://user-images.githubusercontent.com/424694/138196632-0135429b-08e6-4cde-8306-f8ac9eca63b7.png)

```
AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)


NullReferenceException: Object reference not set to an instance of an object.
   at ProcessMemoryDataFinder.Structured.StructuredMemoryReader.ReadValueForPropInMemory(Nullable`1 classAddress, PropInfo prop, TypeCacheEntry cacheEntry)
   at ProcessMemoryDataFinder.Structured.StructuredMemoryReader.ResolveProp[T](T readObj, Nullable`1 classAddress, PropInfo prop, TypeCacheEntry cacheEntry)
   at ProcessMemoryDataFinder.Structured.StructuredMemoryReader.TryInternalRead[T](T readObj, Nullable`1 classAddress, String classPath)
   at ProcessMemoryDataFinder.Structured.StructuredMemoryReader.TryRead[T](T readObj)
   at OsuMemoryEventSource.MemoryDataProcessor.Tick(OsuStatus status, OsuMemoryStatus rawStatus, StructuredOsuMemoryReader reader)
   at OsuMemoryEventSource.MemoryListener.Tick(List`1 clientReaders, Boolean sendEvents)
   at OsuMemoryEventSource.OsuMemoryEventSourceBase.MemoryWorker()
```

**Comment by cchamberlain** [comment]
FYI I rolled back to v210817.21 and it has not crashed yet so pretty sure its something new.

**Comment by Piotrekol** [comment]
reopen and provide requested details if this still happens.
