### ISSUE TITLE
add error handling for gamma range outside 0-100 

### ISSUE THREAD

**Issue by Epikest** [Piotrekol/StreamCompanion#376]
currently, it will just crash if you try to use settings from an older version of StreamCompanion
```
ArgumentOutOfRangeException: Value of '105' is not valid for 'Value'. 'Value' should be between 'Minimum' and '$Maximum'. (Parameter 'value')
Actual value was 105.
   at System.Windows.Forms.TrackBar.set_Value(Int32 value)
   at Gamma.GammaSettings.PopulateForm(GammaRange gammaRange)
   at Gamma.GammaSettings.listBox_gammaRanges_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
![image](https://user-images.githubusercontent.com/45499416/226156424-f144aafa-f442-4d99-9cfa-2eb7003c6041.png)
![image](https://user-images.githubusercontent.com/45499416/226156428-0e41b282-ed5a-4596-b599-61209c3f1c4e.png)

**Comment by Piotrekol** [comment]
Shouldn't be possible if user didn't edit their settings.ini manually - previous range was 0.228 - 4.46 which was mapped to 100 - 0

I guess clamping the value on conversion wouldn't hurt
