### ISSUE TITLE
Streamcompanion crashes directly after starting up

### ISSUE THREAD

**Issue by Turbotondel** [Piotrekol/StreamCompanion#49]
Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at osu.Game.Rulesets.Taiko.Objects.TaikoHitWindows.SetDifficulty(Double difficulty)
   at osu.Game.Rulesets.Objects.HitObject.ApplyDefaultsToSelf(ControlPointInfo controlPointInfo, BeatmapDifficulty difficulty)
   at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, BeatmapDifficulty difficulty)
   at osu.Game.Beatmaps.WorkingBeatmap.GetPlayableBeatmap(RulesetInfo ruleset)
   at PpCalculator.PpCalculator.Calculate(Nullable`1 time, Dictionary`2 categoryAttribs)
   at BeatmapPpReplacements.PpReplacements.GetPp(PpCalculator ppCalculator, Double acc, String mods, Int32 score)
   at BeatmapPpReplacements.PpReplacements.GetMapReplacements(MapSearchResult map)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.GetMapReplacements(MapSearchResult mapSearchResult)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.ProcessMapResult(MapSearchResult mapSearchResult)

**Comment by Piotrekol** [comment]
Already aware, for whatever reason that dll is missing in setup, when building locally it's there.

**Comment by Piotrekol** [comment]
https://github.com/Piotrekol/StreamCompanion/releases/tag/v190314.19
