### ISSUE TITLE
Going to run the companion and this error happens

### ISSUE THREAD

**Issue by Shiori857** [Piotrekol/StreamCompanion#76]
Field not found: 'StreamCompanionTypes.DataTypes.MapSearchResult.Action'.
   at osuOverlay.IngameOverlay.SetNewMap(MapSearchResult map)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.SetNewMap(MapSearchResult map)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MainMapDataGetter.ProcessMapResult(MapSearchResult mapSearchResult)
   at osu_StreamCompanion.Code.Core.Maps.Processing.MapStringFormatter.ConsumerTask()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by Piotrekol** [comment]
Do a full SC reinstall
